server:
  port: 8085
  
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/bank_management
    username: root
    password: saurav 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true  
active:
   banks:
      - name: HDFC
        host: localhost
        port: 1234
      - name: Yes Bank
        host: localhost
        port: 1234
      - name: SBI
        host: localhost
        port: 1234
      - name: PNB
        host: localhost
        port: 1234
      - name: Union Bank
        host: localhost
        port: 1234
      - name: Vijaya Laxmi
        host: localhost
        port: 1234
      - name: Bandhan
        host: localhost
        port: 1234
        

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    file:  "%d{yyyy-MM-dd HH:mm:ss}------- %-5level----------- - %msg%n" 