server:
  port: 8800
spring:  application:    name: gateway-service

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true  ignored-services:  - "*"
  routes:    account-service:
      path: /account/**
      service-id: account-service
    login-service:
      path: /login/**
      service-id: login-service
    mutual-fund-service:
      path: /mutualfund/**
      service-id: mutual-fund-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 